Vermonster/fhir-kit-client

lib/smart.js
test/client_test.js

When working through SMART workflow examples, these would be nice to have a URL objects.

Make URL objects

---

.coveralls.yml
.travis.yml
README.md
package.json
test/client_test.js
test/fixtures/no-smart-oauth-uri-capability-statement.json
test/fixtures/valid-capability-statement.json
yarn.lock

Sets up `coveralls` so that we have code coverage reports. Additionally, adds more test coverage.

Install coveralls

---

CODE_OF_CONDUCT.md
README.md
package.json

Add CoC using info@vermonster.com as contact.

Add code of conduct from contributor-covenant.org

---

.editorconfig
.eslintrc.json
test/fixtures/empty-search-results.json
test/fixtures/patient-version-not-found.json

EditorConfig:
http://editorconfig.org/

Use Editorconfig

---

lib/client.js
lib/http-client.js
lib/reference-resolver.js
lib/smart.js
lib/utils.js

Edited some examples so that they were consistent with our linting rules, as well as some other minor documentation edits.

Update docs to use our js styles

---

CONTRIBUTING.md
README.md
issue_template.md

Language and issue flow adapted from open source projects like Atom.io and Rails.

25 - Contribution guidelines

---

.eslintrc.json
test/.eslintrc.json
test/client-test.js

See: https://mochajs.org/#arrow-functions

Do not use fat-arrows in mocha tests

---

.gitignore
README.md
package.json

Trello card:
https://trello.com/c/zPrek6iy/10-publish-the-node-module
in `.npmrc`:
```
//registry.npmjs.org/:_authToken=abcdefab-abcd-abcd-abcd-abcdefabcdef
```
(http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules)
How to Work with Authentication Tokens
-----------------------------------------
https://docs.npmjs.com/getting-started/working_with_tokens
How to Use Two-Factor Authentication
---------------------------------------
https://docs.npmjs.com/getting-started/using-two-factor-authentication
Semantic Versioning (before publish)
---------------------------------------
```
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]
```
https://docs.npmjs.com/cli/version

configure publishing to npmjs

---

README.md
lib/client.js

General updates, and truncate the examples in the README (keep them quick, full examples in the JS Documentation).

Updates to README

---

README.md
examples/README.md

Add links to the create react app in the readme and fix some broken links.

Link to create react app

---

examples/confidential-smart-ehr/confidential-smart-ehr-launch.js
examples/confidential-smart-ehr/package.json
examples/confidential-smart-ehr/yarn.lock
examples/public-smart-ehr/package.json
examples/public-smart-ehr/public-smart-ehr-launch.js
examples/public-smart-ehr/yarn.lock
examples/smart-standalone/package.json
examples/smart-standalone/smart-standalone-launch.js
examples/smart-standalone/yarn.lock

This addresses #79 . This branch makes OAuth2-related updates to fix the examples.

Fix examples

---

examples/README.md

This supersedes https://github.com/Vermonster/fhir-kit-client/pull/97

Clarify example README

---

README.md
lib/client.js
lib/http-client.js

Adds support for TLS key/certificate authentication, as used by the Finnish Kanta services (see https://www.kanta.fi/en/system-developers/my-kanta-pages-phr).

Add TLS key/certificate support

---

package.json

Use npm with nyc for coverage.

---

.travis.yml
examples/cds-hooks/cds-hooks-launch.js
lib/client.js
lib/utils.js
package.json
yarn.lock

Update dependencies to fix several security warnings

Security fixes

---

lib/http-client.js
test/client-test.js

This addresses https://github.com/Vermonster/fhir-kit-client/issues/129

Content-type headers if missing

---

lib/smart.js

Remove since we are node 10+ now.

Remove require, since we are node 10+ now

---

lib/client.js
lib/deprecations.js
lib/fetch-queue.js
lib/smart.js
package.json
test/client-test.js
test/fixtures/well-known.json
test/smart-test.js
test/test-utils.js
yarn.lock

WIP for smart and oidc wellknown

Support wellknown

---

lib/client.js
lib/http-client.js
lib/logging.js
package.json
test/client-test.js
yarn.lock

This logs the headers, as we switched to fetch polyfill a while back (fixes problems found in #138 and #135).

Better logging

---

CHANGELOG.md
README.md
index.d.ts
package.json
yarn.lock

Add basic types

---

lib/client.js
lib/utils.js
test/client-test.js

This prevents possible url injections.

Throw error is the resourceType is not valid

---

index.d.ts
lib/client.js
package.json
test/type.test.ts
tsconfig.json
types/externals.d.ts
types/index.d.ts
yarn.lock

Addressing problems in https://github.com/Vermonster/fhir-kit-client/issues/158

Fix typescript issues
